In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import signal
import pycmap

In [2]:
# set up API 
api = pycmap.API(token='68fbf4b0-22f4-11ec-a2c9-a3d02432460d')

In [5]:
table_name = "tblMGL1704_Gradients2_IFCB_Abundance"

In [6]:
# variables in the dataset 
api.get_dataset_metadata(table_name)

,Variable,Table_Name,Long_Name,Unit,Make,Sensor,Process_Level,Study_Domain,Temporal_Resolution,Spatial_Resolution,...,Dataset_Short_Name,Data_Source,Distributor,Dataset_Description,Acknowledgement,Dataset_ID,ID,Visualize,Keywords,Refrences
0,Sample,tblMGL1704_Gradients2_IFCB_Abundance,samples filename from IFCB,NaN,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5712,NaN,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
1,Acanthoica,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Acanthoica,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5713,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
2,Acanthometron,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Acanthometron,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5714,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
3,Acanthostaurus,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Acanthostaurus,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5715,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
4,Achnanthes,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Achnanthes,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5716,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Uronema,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Uronema,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5879,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
168,Warnowia,tblMGL1704_Gradients2_IFCB_Abundance,Abundance of cells in genus Warnowia,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5880,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
169,Total_Cells,tblMGL1704_Gradients2_IFCB_Abundance,Total abundance of cells across all genera,cells L-1,Observation,Flow Cytobot,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5881,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
170,Temperature,tblMGL1704_Gradients2_IFCB_Abundance,Temperature from underway thermosalinograph,degrees C,Observation,Thermosalinograph,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5882,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."
171,Salinity,tblMGL1704_Gradients2_IFCB_Abundance,Salinity from underway thermosalinograph,psu,Observation,Thermosalinograph,Reprocessed,Biology+Biogeography,Irregular,Irregular,...,Gradients2_MGL1704_IFCB_Abundance,"Angel White Lab, University of Hawaii at Manoa","Angel White Lab, University of Hawaii at Manoa",The Imaging FlowCytoBot (IFCB) is an in situ a...,These Simons Collaboration on Ocean Processes ...,375,5883,1.0,"abundance, angel white lab, cell abundance, ce...","http://ifcb-data.soest.hawaii.edu/IFCB_NPTZ, [..."

In [7]:
# columns in the dataset 
api.columns(table_name)

         Columns
0           time
1            lat
2            lon
3          depth
4         Sample
..           ...
171      Uronema
172     Warnowia
173  Total_Cells
174  Temperature
175     Salinity

[176 rows x 1 columns]

In [8]:
# top 5 rows in the dataset 
api.head(table_name)

,time,lat,lon,depth,Sample,Acanthoica,Acanthometron,Acanthostaurus,Achnanthes,Actinoptychus,...,Trichodesmium,Tropidoneis,Umbellosphaera,Umbilicosphaera,Undella,Uronema,Warnowia,Total_Cells,Temperature,Salinity
0,2017-05-30T22:39:00,29.70660,-158.0012,5,D20170530T223928_IFCB000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,403.694532,NaN,NaN,NaN,NaN,3835.098050,22.60010,33.23830
1,2017-05-30T23:03:00,29.77720,-158.0001,5,D20170530T230246_IFCB000,NaN,202.716747,NaN,NaN,NaN,...,NaN,NaN,608.150241,NaN,NaN,NaN,NaN,7905.953140,22.65945,33.37695
2,2017-05-30T23:26:00,29.84345,-158.0004,5,D20170530T232604_IFCB000,405.147569,NaN,NaN,NaN,NaN,...,NaN,NaN,607.721354,NaN,NaN,NaN,NaN,8508.098956,22.58700,33.29670
3,2017-05-30T23:49:00,29.91305,-157.9991,5,D20170530T234922_IFCB000,610.447502,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12412.432540,22.54985,33.34585
4,2017-05-31T00:13:00,29.98565,-157.9989,5,D20170531T001240_IFCB000,202.177498,NaN,NaN,NaN,NaN,...,NaN,NaN,606.532493,NaN,NaN,NaN,NaN,7076.212418,22.48495,33.08935